zookeeper:
  connection_string: 18.235.45.11:2181

jwt:
  secret: YourJWTSecretPassword
  timeout_seconds: 1800

cors:
  allowed_origins: '*'
  allowed_headers: '*'
  allowed_methods: '*'

users:
  users_details:
    -
      name: Admin
      password: Admin
