import { NodeDataType } from '../autogenerated/model/NodeDataType';

const pathSeparator: string = '~~';

export class Json {
  public type: string;
  public server: string;
  public client: string;
  public application: string;
  public instObj: JSON;
  

  constructor() {
 
  }


  
}
